-include .env


build :; forge build

deploy-sepolia:
	forge script script/DeployRaffle.s.sol --rpc-url $(S_RPC_URL) --private-key $(PRIVATE_KEY) --broadcast --verify --etherscan-api-key $(ETHER_SCAN_API_KEY) --priority-gas-price 1